import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT_DIR = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "../..",
);
const OUTPUT_PATH = path.join(
  ROOT_DIR,
  "workers/umami-pageviews/src/allowed-paths.generated.ts",
);
const STATIC_PAGEVIEW_PATH_PREFIXES = ["/blog", "/projects"];

async function main() {
  const sortedPrefixes = [...STATIC_PAGEVIEW_PATH_PREFIXES].sort(
    (left, right) => left.localeCompare(right),
  );

  const output = [
    "// This file is generated by `bun run pageviews:sync`.",
    "// Do not edit manually.",
    "",
    "export const ALLOWED_PAGEVIEW_PATH_PREFIXES = [",
    ...sortedPrefixes.map((pagePath) => `  ${JSON.stringify(pagePath)},`),
    "] as const;",
    "",
  ].join("\n");

  await mkdir(path.dirname(OUTPUT_PATH), { recursive: true });
  await writeFile(OUTPUT_PATH, output, "utf8");

  console.log(
    `Synced ${sortedPrefixes.length} pageview path prefix(es) to ${path.relative(ROOT_DIR, OUTPUT_PATH)}.`,
  );
}

await main();
